config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :customers, only: [:index, :show] do
    collection do
      match :test, via: [:get, :post]
    end
    member do
      post :send_message
    end
  end
end

app/models/agent.rb
class Agent < ApplicationRecord
  has_many :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :customer
  belongs_to :agent, optional: true
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
    @agents = Agent.all
  end

  def send_message
    customer = Customer.find(params[:id])
    msg_body = params[:message]
    agent_id = params[:agent].to_i
    agent = Agent.find(agent_id)

    msg = Message.create(
      customer: customer,
      agent: agent,
      body: msg_body
    )

    redirect_to customer_path, notice: "Sent message #{msg.body} for customer #{customer.name} (id #{customer.id})"
  end

  def test
    @customers = Customer.all

    if request.post?
      msg_body = params[:message]
      customer_id = params[:customer_id]
      customer_name = params[:customer_name]

      customer = customer_id.present? ? Customer.find(customer_id) : Customer.create(name: customer_name)

      msg = Message.create(customer: customer, body: msg_body)
      return redirect_to test_customers_path, notice: "Sent message #{msg.body} for customer #{customer.name} (id #{customer.id})"
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/index.html.erb
<ul>
  <% @customers.each do |customer| %>
   <li><%= link_to customer.name, customer_path(customer) %></li>
  <% end %>
</ul>

app/views/customers/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<ul>
  <% @customer.messages.each do |message| %>
    <li>
      <%= message.created_at %>
      <% if message.agent %>
        <%= "#{message.agent.name} (Agent)" %>
      <% else %>
        <%= "#{message.customer.name} (Customer)" %>
      <% end %>

      <%= message.body %>
    </li>
  <% end %>
</ul>

<%= form_with url: send_message_customer_path, method: :post do |form| %>

  <%= form.label :message, "Enter message here..." %><br>
  <%= form.text_field :message %>

  <%= form.select :agent, @agents.map { |agent| [agent.name, agent.id] } %>

  <%= form.submit %>
<% end %>

app/views/customers/test.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= form_with url: test_customers_path, method: :post do |form| %>
  <br>
  <%= form.label :message, "Enter message here..." %>
  <%= form.text_field :message %>
  <br>
  <%= form.label :customer_name, "Name (if new customer)" %>
  <%= form.text_field :customer_name %>

  <%= form.select :customer_id, [["New customer ", nil]] + @customers.map { |customer| [customer.name, customer.id] } %>

  <%= form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMessagingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>